
<?php
class formCategories{
function showForms($task){
 $taskOriginal =$task;
 ?>
 

<form method='post' action='addCategoria'>
    <div>
        <label for='categoria'>Nombre Categoria</label>
        <input type='text' class='form-control' id='categoria' name='categoria' required>
    </div>

    <button type='submit' class='btn btn-primary'>Agregar</button>
  
</form>

<h4>Editar</h4>

<form method='post' action='editarCategoria'>
    <div class='form-group'>
        <label for='nombreCate'>Categoria</label>
        <select type="int" name="nombreCate" id="nombreCate">
        <?php if (!empty($task) && is_array($task)): ?>
              <?php foreach($task as $task): ?>
        <option value="<?= $task->id ?>"><?=$task->nombre_categoria?></option>
             <?php endforeach; ?>
        <?php else: ?>
            <option value="">No hay categorías disponibles</option>
        <?php endif; ?>

        </select>   
    </div>
    <div class='form-group'>
        <label for='nombrenuevo'>Nuevo nombre

          <input type='text' class='form-control' id='nombrenuevo' name='nombrenuevo' required>
          
       </label>
    </div>
    
    <button type='submit' class='btn btn-primary'>Editar</button>  
</form>
<?php $task = $taskOriginal ?>
        
<form method='post' action='eliminarCategoria'>
    <div class='form-group'>
        <label for='eliminarACategoria'>Categoria</label>
        <select type="int" name="eliminarCategoria" id="eliminarCategoria">
                <?php if (!empty($task) && is_array($task)): ?>
                    <?php foreach($task as $task): ?>
                        <option value="<?= $task->id ?>"><?= $task->nombre_categoria?></option>
                    <?php endforeach; ?>
                <?php else: ?>
                        <option value="">No hay categorías disponibles</option>
                <?php endif; ?>
        </select>    
       <button type='submit' class='btn btn-primary'>Eliminar</button>
   </div>    
</form>

<?php


}
}
