
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
  
</body>
</html>


<form class="mb-3" action="insert" method="post">
        
   <input  id="nombre" name="nombre" placeholder="nombre">
   <input  id="apellido" name="apellido" placeholder="apellido">
   <input  id="nombre_producto" name="nombre_producto" placeholder="nombre del producto">
   <select name="tipoDeCompra" id="tipoDeCompra">
      <?php foreach ($task as $task) {  ?>
            <option value="<?php echo $task->id?>"> <?php echo $task->nombre_categoria?></option>
      <?php 
        }?>
    </select>
    <button type="submit" class="btn btn-primary">Agregar</button>
 </form>


 
 
 